### ISSUE TITLE
Installed plugin, no preview..

### ISSUE THREAD

**Issue by dmrickey** [johnknoop/vscode-handlebars-preview#50]
Whenever I try to show the preview I get this popup
![image](https://user-images.githubusercontent.com/3664822/175663985-5ade8270-029a-4114-a6d0-9cd5125f93e9.png)

**Comment by johnknoop** [comment]
Hi @dmrickey 

I've never seen that before. Would you mind providing me with the Extension Host log files? You can find them using `cmd-shift-p` -> Search `Show Logs` -> `Extension Host`. Hopefully there might be more information in there.

Cheers

**Comment by dmrickey** [comment]
```
[2022-06-28 11:33:57.682] [exthost] [error] Error: command 'vscode.previewHtml' not found
    at v._tryExecuteCommand (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1706:3532)
    at v.executeCommand (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1706:3414)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) handlebarsPreview.preview {"value":"chaliy.handlebars-preview","_lower":"chaliy.handlebars-preview"}
    ```

**Comment by johnknoop** [comment]
@dmrickey 

Sorry for the late response. It seems the error is happening in the VS Code runtime before the extension is invoked.

Would you mind describing your setup? Are you running this from a normal VS Code installation? And would you mind sharing your steps to reproduce it?

Thanks
